// 遊戲紀錄詳情文字
export const gameTitleMap = {
  user_name: '用户名',
  round: '轮次',
  // BetTime: '投注时间',
  CurrentPrice: '当期价格',
  // EndTime: '结束时间',
  ExpirePrice: '到期价格',
  // Odds: '赔率',
  // OrderNo: '订单号',
  ProCNName: '品种中文',
  ProENName: '品种英文',
  // RuleType: '玩法',
  UpDown: '涨跌',
  logDetail: '备注',
  // BetTime: '下注时间',
  Cmd: '下单翻译指令',
  EndTime: '派彩时间/有效時間',
  Numbers: '开奖号码/有效号码',
  Odds: '赔率',
  OrderNo: '记录号',
  PlayValue: '所选号码/投票号码',
  RuleType: '下单类型/票選類型',
  SRate: '投注时间/投票时间',
  round_no: '期數',
  // BetTime: '投注时间',
  PayoutTime: '结算时间',
  Username: '用户名',
  HostID: '桌台ID',
  Detail: '电子游艺用作游戏名称',
  // GameID: '游戏编号',
  // Round: '局',
  Set: '靴',
  BetID: '下注ID',
  Rolling: '洗碼量',
  Balance: '投注後的馀额',
  ResultAmount: '结算',
  // GameType: '游戏类型',
  BetType: '下注类型',
  BetSource: '下注平台',
  State: '下注是否成功',
  LottoName: '游戏名称/投资名称',
  BillNo: '注单流水号',
  // GameCode: '游戏局号',
  NetAmount: '玩家输赢额度',
  BetTime: '投注时间',
  GameType: '游戏类型',
  ValidBetAmount: '有效投注额度',
  PlayType: '玩法类型',
  TableCode: '桌子编号',
  // PlatformType: '平台类型',
  Round: '平台内的大厅类型',
  TradeNo: ' 交易编号',
  PlatformType: ' 平台类型',
  SceneID: '场景号',
  SceneStartTime: '场景开始时间',
  SceneEndTime: '场景结束时间',
  Roomid: '房间号',
  Roombet: '房间倍率',
  Cost: '投注额度',
  Earn: '派彩',
  Type: '转账类别',
  Jackpotcomm: '场景彩池投注',
  TransferAmount: '转账额度',
  PreviousAmount: '转账前额度',
  CurrentAmount: '当前额度',
  CreationTime: '记录时间',
  GameCode: '游戏局号(通常为空)',
  GameID: '游戏局号',
  ServerID: '房间 ID',
  KindID: '游戏 ID',
  TableID: '桌子号',
  ChairID: '椅子号',
  CellScore: '有效下注',
  AllBet: '总下注',
  Profit: '盈利',
  CardValue: '手牌公共牌',
};
  